# Generated by Django 6.0 on 2025-12-24 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateField(default=datetime.datetime.now)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('Fun', 'Fun'), ('SC', 'Science'), ('HC', 'Historical')], max_length=3)),
            ],
        ),
    ]
